### ISSUE TITLE
Carousel buttons look weird

### ISSUE THREAD

**Issue by thakkarparth007** [delta/Website-NITT-2016#7]
There's no padding which makes them look ugly. We could either make them circular, or full-height boxes, or simply add proper padding.

With circular, this is how it looks: (Only the right side button is shown properly in the image)

![image](https://cloud.githubusercontent.com/assets/747423/14941079/f192a2d0-0fac-11e6-93b4-349d907a0275.png)

**Comment by tushar-rishav** [comment]
Or maybe just make the background of button transparent. That'd suffice I think.
